### ISSUE TITLE
Hue and LIFX sync isn't working - 5.0.0-preview.8.20407.11

### ISSUE THREAD

**Issue by BhaskinsWR** [isaacrlevin/PresenceLight#145]
**Describe the bug**
Desktop app authenticates to O365, Hue, and LIFX properly - but will not sync color, windows theme, or Teams presence - light color unchanged. Uninstalled / reinstalled, no resolution.

**To Reproduce**
Load app, authenticate, manually change colors / sync targets.

## Further details
- OS: Win10 Pro - 10.0.19041 build 19041
- PresenceLight App Type - Desktop
- PresenceLight Build - Store
- PresenceLight Version - 3.0.40.0, 5.0.0-preview.8.20407.11
- Did you clear settings.json? - Yes (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version - 4.8.04084

**Comment by cconrado** [comment]
Also happening to me and also tried uninstalling.

As a side note the statuses are unreadable
![image](https://user-images.githubusercontent.com/9168464/92802654-4f4a8700-f37c-11ea-8672-0e1048c7802d.png)

**Comment by BhaskinsWR** [comment]
Update - installed ASP 5 preview 8 = no resolution. Downgraded PL to 3.0.19 and we're back in action. Noticed one other bug in 3.0.4: PL missing from Startup Apps.

Sync issue aside, I really like the adds in 3.0.4 - ability to change light behavior based on offline etc. status = really smart, much appreciated!

**Comment by BhaskinsWR** [comment]
> Also happening to me and also tried uninstalling.
> 
> As a side note the statuses are unreadable
> ![image](https://user-images.githubusercontent.com/9168464/92802654-4f4a8700-f37c-11ea-8672-0e1048c7802d.png)

@cconrado - maybe a scaling issue? I'm at 125% on 3440/2560x1440 monitors and text is clear, fwiw..

**Comment by sborg-ms** [comment]
Same issue here - this morning it didnt sync and the lifx light remained off. (Nightly PresenceLight Version - 3.0.40.0, 5.0.0-preview.8.20407.11)

**Comment by chrsmrtn-** [comment]
Same here. I attempted re-install. Revoked app access in LIFX and got a new token. Now not listing any lights in my LIFX account

![image](https://user-images.githubusercontent.com/5657979/92949183-828a2600-f40f-11ea-8a9e-057a5a114210.png)

**Comment by isaacrlevin** [comment]
@chrsmrtn- can you open Fiddler, than the app and see what happens here? I just installed latest store version and all worked as expected

**Comment by chrsmrtn-** [comment]
@isaacrlevin hey I figured it out. Turns out the device was no longer assigned to my LIFX account even though it was still visible in the Android App. I figured this out by looking at the list of devices on my account at cloud.lifx.com.  I'm updating to the latest version now to see if I still have issues syncing my status.

I've had this "disconnecting device" issue a couple of times. I'm not entirely sure what causes it, but I suspect it may have something to do with having my google home also connected and controlling the device.  That's a lifx issue, so i'll follow up with them if I can pinpoint a possible cause.

Thanks for reaching back out

**Comment by chrsmrtn-** [comment]
Okay, got back on the latest version, and indeed I'm still experiencing the issue reported by @BhaskinsWR .  I tried to capture network traffic and didn't see any. Not sure if this is because of Fiddler Everywhere (new). I remember the other version of Fiddler needing to do special things to capture windows store apps traffic, but that was back in like windows 8 days and not sure if that was since been improved upon in subsequent versions of Fiddler.

**Comment by chrsmrtn-** [comment]
Okay, I reverted and see the graph queries for presense now. I'm back on version 3.0.19

**Comment by isaacrlevin** [comment]
Can you try the latest nightly build?

**Comment by sborg-ms** [comment]
Went to install latest  - was on Version - 3.0.40.0 and noted it was going to Version - 3.0.42.0  BUT it did not that i had a NEWER version already installed - did i want to continue?  Proceeding and it failed with -

App installation failed with error message: Appinstaller operation failed with error code 0x80190193. Detail: Forbidden (403). (0x80190193)

**Comment by sborg-ms** [comment]
FYI - Version 3.0.43  cleanly installed. and now LIFX lights are back working... 
cheers

**Comment by chrsmrtn-** [comment]
@isaacrlevin updated to nightly and it's working just fine there

**Comment by BhaskinsWR** [comment]
3.0.43 installed, working here. Nice work, thanks!
