### ISSUE TITLE
Docker: AADSTS50011

### ISSUE THREAD

**Issue by icetre-normal** [isaacrlevin/presencelight#755]
Tried to sign into my corporate account anormal@1111systems.com; got all the way through only to error here. Not sure what to do here; since I have almost no ability to configure this app via azure. 

Request Id: 4a484a80-5fb2-4f97-9410-efb996198a00
Correlation Id: 4ec72077-0740-4398-97a3-effd8786550e
Timestamp: 2022-10-25T17:53:48Z
Message: AADSTS50011: The redirect URI 'http://192.168.0.60:3838/signin-oidc' specified in the request does not match the redirect URIs configured for the application 'f8119f58-4523-44c1-ab72-b2e0c815bd6a'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

**Comment by isaacrlevin** [comment]
You need to use one of the pre-defined redirect URLS. I don't have the ability to support all the possible redirect URLs since Azure AD does not work that way. Set your IP/DNS of your image to one of below and it should work

![image](https://user-images.githubusercontent.com/8878502/203625985-da972c2b-aa21-48ea-9a5b-28764fe8d9d1.png)
